### ISSUE TITLE
how to include mpi.h?

### ISSUE THREAD

**Issue by MonaJoshi** [njskalski/ParallelShortestPaths#1]
floyd-warshall-par.c:4:17: fatal error: mpi.h: No such file or directory
compilation terminated.

**Comment by njskalski** [comment]
what system are you using? you have to install open mpi library for this program to work.

**Comment by MonaJoshi** [comment]
I am using Dell Vostro 3546. How to install?

*Regards,*
*MONICA JOSHI *

**Comment by njskalski** [comment]
I apologize if I wasn't specific enough: I ment operating systems. Do you use Windows, Linux, Mac?

**Comment by MonaJoshi** [comment]
It's Ubuntu

**Comment by njskalski** [comment]
sudo apt-get install libopenmpi-dev
works on 16.04. Does that help?
